optimizer:
  name: 'AdamW'
  parameters:
    lr: 0.0003
    weight_decay: 0.00001
criterion:
  name: 'Focal'
  parameters:
    gamma: 2
scheduler:
  name: 'OneCycle'
  parameters:
    max_lr: 0.0003
    pct_start: 0.05
    anneal_strategy: 'cos'
    base_momentum: 0.85
    max_momentum: 0.9
num_epochs: 15
train_batch: 128
val_batch: 256
num_workers: 48
logs_save_path: '../../logs'